"""Escrow template — trustless SPL token escrow with buyer/seller flow."""

from src.parser import to_rust_name


def ESCROW_TEMPLATE(program_name: str) -> str:
    mod = to_rust_name(program_name)
    return f'''// Generated by AnchorScaffold — LixerDev
// Template: SPL Token Escrow | Program: {program_name}
// Flow: create → fulfill → approve_release | cancel

use anchor_lang::prelude::*;
use anchor_spl::token::{{self, Token, TokenAccount, Mint, Transfer, CloseAccount}};

declare_id!("11111111111111111111111111111111");

#[program]
pub mod {mod} {{
    use super::*;

    /// Buyer creates an escrow, deposits tokens into the vault.
    /// `expiry_duration` seconds before the escrow can be cancelled by buyer.
    pub fn create_escrow(
        ctx: Context<CreateEscrow>,
        escrow_id: u64,
        amount: u64,
        seller: Pubkey,
        expiry_duration: i64,
    ) -> Result<()> {{
        require!(amount > 0, ErrorCode::ZeroAmount);
        let clock = Clock::get()?;
        let escrow = &mut ctx.accounts.escrow;
        escrow.buyer = ctx.accounts.buyer.key();
        escrow.seller = seller;
        escrow.mint = ctx.accounts.mint.key();
        escrow.amount = amount;
        escrow.fulfilled = false;
        escrow.released = false;
        escrow.cancelled = false;
        escrow.created_at = clock.unix_timestamp;
        escrow.expires_at = clock.unix_timestamp.checked_add(expiry_duration).ok_or(ErrorCode::Overflow)?;
        escrow.escrow_id = escrow_id;
        escrow.bump = ctx.bumps.escrow;

        token::transfer(
            CpiContext::new(
                ctx.accounts.token_program.to_account_info(),
                Transfer {{
                    from: ctx.accounts.buyer_ata.to_account_info(),
                    to: ctx.accounts.vault.to_account_info(),
                    authority: ctx.accounts.buyer.to_account_info(),
                }},
            ),
            amount,
        )?;

        emit!(EscrowCreated {{
            escrow_id,
            buyer: escrow.buyer,
            seller: escrow.seller,
            amount,
            expires_at: escrow.expires_at,
        }});
        Ok(())
    }}

    /// Seller marks the escrow as fulfilled (off-chain delivery confirmed).
    pub fn fulfill(ctx: Context<Fulfill>) -> Result<()> {{
        let escrow = &mut ctx.accounts.escrow;
        require!(!escrow.fulfilled, ErrorCode::AlreadyFulfilled);
        require!(!escrow.cancelled, ErrorCode::EscrowCancelled);
        require!(
            ctx.accounts.seller.key() == escrow.seller,
            ErrorCode::NotSeller
        );
        escrow.fulfilled = true;
        emit!(EscrowFulfilled {{ escrow_id: escrow.escrow_id, seller: escrow.seller }});
        Ok(())
    }}

    /// Buyer approves release — funds are sent to seller.
    pub fn approve_release(ctx: Context<ApproveRelease>) -> Result<()> {{
        let escrow = &ctx.accounts.escrow;
        require!(escrow.fulfilled, ErrorCode::EscrowNotFulfilled);
        require!(!escrow.released, ErrorCode::AlreadyReleased);
        require!(!escrow.cancelled, ErrorCode::EscrowCancelled);
        require!(
            ctx.accounts.buyer.key() == escrow.buyer,
            ErrorCode::NotBuyer
        );

        let seeds: &[&[u8]] = &[
            b"escrow",
            escrow.buyer.as_ref(),
            &escrow.escrow_id.to_le_bytes(),
            &[escrow.bump],
        ];
        let signer = &[seeds];

        token::transfer(
            CpiContext::new_with_signer(
                ctx.accounts.token_program.to_account_info(),
                Transfer {{
                    from: ctx.accounts.vault.to_account_info(),
                    to: ctx.accounts.seller_ata.to_account_info(),
                    authority: ctx.accounts.escrow.to_account_info(),
                }},
                signer,
            ),
            escrow.amount,
        )?;

        ctx.accounts.escrow.released = true;
        emit!(EscrowReleased {{
            escrow_id: escrow.escrow_id,
            seller: escrow.seller,
            amount: escrow.amount,
        }});
        Ok(())
    }}

    /// Buyer cancels escrow after expiry and reclaims funds.
    pub fn cancel(ctx: Context<Cancel>) -> Result<()> {{
        let escrow = &ctx.accounts.escrow;
        require!(!escrow.released, ErrorCode::AlreadyReleased);
        require!(!escrow.cancelled, ErrorCode::EscrowCancelled);
        require!(
            ctx.accounts.buyer.key() == escrow.buyer,
            ErrorCode::NotBuyer
        );
        let clock = Clock::get()?;
        require!(
            clock.unix_timestamp >= escrow.expires_at || !escrow.fulfilled,
            ErrorCode::NotExpiredYet
        );

        let seeds: &[&[u8]] = &[
            b"escrow",
            escrow.buyer.as_ref(),
            &escrow.escrow_id.to_le_bytes(),
            &[escrow.bump],
        ];
        let signer = &[seeds];

        token::transfer(
            CpiContext::new_with_signer(
                ctx.accounts.token_program.to_account_info(),
                Transfer {{
                    from: ctx.accounts.vault.to_account_info(),
                    to: ctx.accounts.buyer_ata.to_account_info(),
                    authority: ctx.accounts.escrow.to_account_info(),
                }},
                signer,
            ),
            escrow.amount,
        )?;

        ctx.accounts.escrow.cancelled = true;
        emit!(EscrowCancelled {{
            escrow_id: escrow.escrow_id,
            buyer: escrow.buyer,
        }});
        Ok(())
    }}
}}

#[derive(Accounts)]
#[instruction(escrow_id: u64)]
pub struct CreateEscrow<\'info> {{
    #[account(
        init,
        payer = buyer,
        space = 8 + EscrowAccount::INIT_SPACE,
        seeds = [b"escrow", buyer.key().as_ref(), &escrow_id.to_le_bytes()],
        bump,
    )]
    pub escrow: Account<\'info, EscrowAccount>,

    #[account(
        init,
        payer = buyer,
        token::mint = mint,
        token::authority = escrow,
        seeds = [b"vault", buyer.key().as_ref(), &escrow_id.to_le_bytes()],
        bump,
    )]
    pub vault: Account<\'info, TokenAccount>,

    pub mint: Account<\'info, Mint>,

    #[account(mut, token::mint = mint, token::authority = buyer)]
    pub buyer_ata: Account<\'info, TokenAccount>,

    #[account(mut)]
    pub buyer: Signer<\'info>,

    pub token_program:  Program<\'info, Token>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
pub struct Fulfill<\'info> {{
    #[account(mut, seeds = [b"escrow", escrow.buyer.as_ref(), &escrow.escrow_id.to_le_bytes()], bump = escrow.bump)]
    pub escrow: Account<\'info, EscrowAccount>,
    pub seller: Signer<\'info>,
}}

#[derive(Accounts)]
pub struct ApproveRelease<\'info> {{
    #[account(mut, seeds = [b"escrow", escrow.buyer.as_ref(), &escrow.escrow_id.to_le_bytes()], bump = escrow.bump)]
    pub escrow: Account<\'info, EscrowAccount>,
    #[account(mut, seeds = [b"vault", escrow.buyer.as_ref(), &escrow.escrow_id.to_le_bytes()], bump)]
    pub vault: Account<\'info, TokenAccount>,
    #[account(mut, token::mint = escrow.mint, token::authority = escrow.seller)]
    pub seller_ata: Account<\'info, TokenAccount>,
    pub buyer: Signer<\'info>,
    pub token_program: Program<\'info, Token>,
}}

#[derive(Accounts)]
pub struct Cancel<\'info> {{
    #[account(mut, seeds = [b"escrow", escrow.buyer.as_ref(), &escrow.escrow_id.to_le_bytes()], bump = escrow.bump)]
    pub escrow: Account<\'info, EscrowAccount>,
    #[account(mut, seeds = [b"vault", escrow.buyer.as_ref(), &escrow.escrow_id.to_le_bytes()], bump)]
    pub vault: Account<\'info, TokenAccount>,
    #[account(mut, token::mint = escrow.mint, token::authority = buyer)]
    pub buyer_ata: Account<\'info, TokenAccount>,
    pub buyer: Signer<\'info>,
    pub token_program: Program<\'info, Token>,
}}

#[account]
#[derive(InitSpace)]
pub struct EscrowAccount {{
    pub buyer:      Pubkey,  // 32
    pub seller:     Pubkey,  // 32
    pub mint:       Pubkey,  // 32
    pub amount:     u64,     // 8
    pub escrow_id:  u64,     // 8
    pub fulfilled:  bool,    // 1
    pub released:   bool,    // 1
    pub cancelled:  bool,    // 1
    pub created_at: i64,     // 8
    pub expires_at: i64,     // 8
    pub bump:       u8,      // 1
}}

#[event]
pub struct EscrowCreated  {{ pub escrow_id: u64, pub buyer: Pubkey, pub seller: Pubkey, pub amount: u64, pub expires_at: i64 }}
#[event]
pub struct EscrowFulfilled {{ pub escrow_id: u64, pub seller: Pubkey }}
#[event]
pub struct EscrowReleased {{ pub escrow_id: u64, pub seller: Pubkey, pub amount: u64 }}
#[event]
pub struct EscrowCancelled {{ pub escrow_id: u64, pub buyer: Pubkey }}

#[error_code]
pub enum ErrorCode {{
    #[msg("Amount must be greater than zero")]          ZeroAmount,
    #[msg("Escrow must be fulfilled before release")]   EscrowNotFulfilled,
    #[msg("Escrow already released")]                   AlreadyReleased,
    #[msg("Escrow already cancelled")]                  EscrowCancelled,
    #[msg("Escrow already marked as fulfilled")]        AlreadyFulfilled,
    #[msg("Only the seller can fulfill this escrow")]   NotSeller,
    #[msg("Only the buyer can perform this action")]    NotBuyer,
    #[msg("Escrow has not expired yet")]                NotExpiredYet,
    #[msg("Arithmetic overflow")]                       Overflow,
}}
'''
