"""Remaining templates: vesting, dao, lottery, multisig, marketplace, launchpad."""

from src.parser import to_rust_name


def VESTING_TEMPLATE(program_name: str) -> str:
    mod = to_rust_name(program_name)
    return f'''// Generated by AnchorScaffold — LixerDev
// Template: Token Vesting | Program: {program_name}
// cliff → linear unlock over duration

use anchor_lang::prelude::*;
use anchor_spl::token::{{self, Token, TokenAccount, Mint, Transfer}};

declare_id!("11111111111111111111111111111111");

#[program]
pub mod {mod} {{
    use super::*;

    /// Create a vesting schedule. Deposits `total_amount` into a locked vault.
    /// Beneficiary can claim tokens after `cliff_duration` seconds,
    /// linearly over `vesting_duration` seconds from start.
    pub fn create_vesting(
        ctx: Context<CreateVesting>,
        vesting_id: u64,
        total_amount: u64,
        cliff_duration: i64,
        vesting_duration: i64,
        beneficiary: Pubkey,
    ) -> Result<()> {{
        require!(total_amount > 0, ErrorCode::ZeroAmount);
        require!(vesting_duration > 0, ErrorCode::InvalidDuration);

        let clock = Clock::get()?;
        let v = &mut ctx.accounts.vesting;
        v.creator = ctx.accounts.creator.key();
        v.beneficiary = beneficiary;
        v.mint = ctx.accounts.mint.key();
        v.total_amount = total_amount;
        v.claimed_amount = 0;
        v.start_ts = clock.unix_timestamp;
        v.cliff_ts = clock.unix_timestamp.checked_add(cliff_duration).ok_or(ErrorCode::Overflow)?;
        v.end_ts = clock.unix_timestamp.checked_add(vesting_duration).ok_or(ErrorCode::Overflow)?;
        v.vesting_id = vesting_id;
        v.cancelled = false;
        v.bump = ctx.bumps.vesting;

        token::transfer(
            CpiContext::new(
                ctx.accounts.token_program.to_account_info(),
                Transfer {{
                    from: ctx.accounts.creator_ata.to_account_info(),
                    to: ctx.accounts.vault.to_account_info(),
                    authority: ctx.accounts.creator.to_account_info(),
                }},
            ),
            total_amount,
        )?;

        emit!(VestingCreated {{
            vesting_id,
            beneficiary,
            total_amount,
            cliff_ts: v.cliff_ts,
            end_ts: v.end_ts,
        }});
        Ok(())
    }}

    /// Beneficiary claims all currently vested tokens.
    pub fn claim(ctx: Context<Claim>) -> Result<()> {{
        let v = &mut ctx.accounts.vesting;
        require!(!v.cancelled, ErrorCode::VestingCancelled);
        require!(
            ctx.accounts.beneficiary.key() == v.beneficiary,
            ErrorCode::Unauthorized
        );

        let clock = Clock::get()?;
        require!(clock.unix_timestamp >= v.cliff_ts, ErrorCode::CliffNotReached);

        let vested = calculate_vested(v, clock.unix_timestamp)?;
        let claimable = vested.checked_sub(v.claimed_amount).ok_or(ErrorCode::Underflow)?;
        require!(claimable > 0, ErrorCode::NothingToVest);

        v.claimed_amount = v.claimed_amount.checked_add(claimable).ok_or(ErrorCode::Overflow)?;

        let seeds: &[&[u8]] = &[
            b"vesting",
            v.beneficiary.as_ref(),
            &v.vesting_id.to_le_bytes(),
            &[v.bump],
        ];
        let signer = &[seeds];
        token::transfer(
            CpiContext::new_with_signer(
                ctx.accounts.token_program.to_account_info(),
                Transfer {{
                    from: ctx.accounts.vault.to_account_info(),
                    to: ctx.accounts.beneficiary_ata.to_account_info(),
                    authority: ctx.accounts.vesting.to_account_info(),
                }},
                signer,
            ),
            claimable,
        )?;

        emit!(TokensClaimed {{ vesting_id: v.vesting_id, beneficiary: v.beneficiary, amount: claimable }});
        Ok(())
    }}
}}

fn calculate_vested(v: &VestingAccount, now: i64) -> Result<u64> {{
    if now >= v.end_ts {{
        return Ok(v.total_amount);
    }}
    let total_duration = (v.end_ts - v.start_ts) as u64;
    let elapsed = (now - v.start_ts) as u64;
    Ok(v.total_amount
        .checked_mul(elapsed).ok_or(ErrorCode::Overflow)?
        .checked_div(total_duration).ok_or(ErrorCode::Overflow)?)
}}

#[derive(Accounts)]
#[instruction(vesting_id: u64, _total: u64, _cliff: i64, _dur: i64, beneficiary: Pubkey)]
pub struct CreateVesting<\'info> {{
    #[account(init, payer = creator, space = 8 + VestingAccount::INIT_SPACE,
        seeds = [b"vesting", beneficiary.as_ref(), &vesting_id.to_le_bytes()], bump)]
    pub vesting: Account<\'info, VestingAccount>,
    #[account(init, payer = creator, token::mint = mint, token::authority = vesting,
        seeds = [b"vault", beneficiary.as_ref(), &vesting_id.to_le_bytes()], bump)]
    pub vault: Account<\'info, TokenAccount>,
    pub mint: Account<\'info, Mint>,
    #[account(mut, token::mint = mint, token::authority = creator)]
    pub creator_ata: Account<\'info, TokenAccount>,
    #[account(mut)] pub creator: Signer<\'info>,
    pub token_program: Program<\'info, Token>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
pub struct Claim<\'info> {{
    #[account(mut, seeds = [b"vesting", vesting.beneficiary.as_ref(), &vesting.vesting_id.to_le_bytes()], bump = vesting.bump)]
    pub vesting: Account<\'info, VestingAccount>,
    #[account(mut, seeds = [b"vault", vesting.beneficiary.as_ref(), &vesting.vesting_id.to_le_bytes()], bump)]
    pub vault: Account<\'info, TokenAccount>,
    #[account(mut, token::mint = vesting.mint, token::authority = beneficiary)]
    pub beneficiary_ata: Account<\'info, TokenAccount>,
    pub beneficiary: Signer<\'info>,
    pub token_program: Program<\'info, Token>,
}}

#[account]
#[derive(InitSpace)]
pub struct VestingAccount {{
    pub creator: Pubkey, pub beneficiary: Pubkey, pub mint: Pubkey,
    pub total_amount: u64, pub claimed_amount: u64, pub vesting_id: u64,
    pub start_ts: i64, pub cliff_ts: i64, pub end_ts: i64,
    pub cancelled: bool, pub bump: u8,
}}

#[event] pub struct VestingCreated {{ pub vesting_id: u64, pub beneficiary: Pubkey, pub total_amount: u64, pub cliff_ts: i64, pub end_ts: i64 }}
#[event] pub struct TokensClaimed {{ pub vesting_id: u64, pub beneficiary: Pubkey, pub amount: u64 }}
#[event] pub struct VestingCancelled {{ pub vesting_id: u64 }}

#[error_code]
pub enum ErrorCode {{
    #[msg("Cliff period not reached")]          CliffNotReached,
    #[msg("No tokens to claim yet")]            NothingToVest,
    #[msg("Vesting schedule was cancelled")]    VestingCancelled,
    #[msg("Unauthorized")]                      Unauthorized,
    #[msg("Amount must be greater than zero")]  ZeroAmount,
    #[msg("Invalid duration")]                  InvalidDuration,
    #[msg("Arithmetic overflow")]               Overflow,
    #[msg("Arithmetic underflow")]              Underflow,
}}
'''


def DAO_TEMPLATE(program_name: str) -> str:
    mod = to_rust_name(program_name)
    return f'''// Generated by AnchorScaffold — LixerDev
// Template: DAO Governance | Program: {program_name}

use anchor_lang::prelude::*;

declare_id!("11111111111111111111111111111111");

const MAX_TITLE_LEN: usize = 100;
const MAX_DESC_LEN: usize = 500;

#[program]
pub mod {mod} {{
    use super::*;

    pub fn initialize_dao(ctx: Context<InitializeDao>, gov_mint: Pubkey, quorum: u64, voting_period: i64) -> Result<()> {{
        let dao = &mut ctx.accounts.dao;
        dao.authority = ctx.accounts.authority.key();
        dao.gov_mint = gov_mint;
        dao.quorum = quorum;
        dao.voting_period = voting_period;
        dao.proposal_count = 0;
        dao.bump = ctx.bumps.dao;
        emit!(DaoInitialized {{ authority: dao.authority, quorum, voting_period }});
        Ok(())
    }}

    pub fn create_proposal(ctx: Context<CreateProposal>, proposal_id: u64, title: String, description: String) -> Result<()> {{
        require!(title.len() <= MAX_TITLE_LEN, ErrorCode::TitleTooLong);
        require!(description.len() <= MAX_DESC_LEN, ErrorCode::DescriptionTooLong);
        let clock = Clock::get()?;
        let p = &mut ctx.accounts.proposal;
        p.dao = ctx.accounts.dao.key();
        p.proposer = ctx.accounts.proposer.key();
        p.proposal_id = proposal_id;
        p.title = title.clone();
        p.description = description;
        p.votes_for = 0;
        p.votes_against = 0;
        p.created_at = clock.unix_timestamp;
        p.ends_at = clock.unix_timestamp.checked_add(ctx.accounts.dao.voting_period).ok_or(ErrorCode::Overflow)?;
        p.executed = false;
        p.cancelled = false;
        ctx.accounts.dao.proposal_count = ctx.accounts.dao.proposal_count.checked_add(1).ok_or(ErrorCode::Overflow)?;
        emit!(ProposalCreated {{ proposal_id, proposer: p.proposer, title, ends_at: p.ends_at }});
        Ok(())
    }}

    pub fn cast_vote(ctx: Context<CastVote>, in_favor: bool, weight: u64) -> Result<()> {{
        require!(weight > 0, ErrorCode::ZeroWeight);
        let clock = Clock::get()?;
        let p = &mut ctx.accounts.proposal;
        require!(!p.executed && !p.cancelled, ErrorCode::ProposalNotActive);
        require!(clock.unix_timestamp < p.ends_at, ErrorCode::VotingPeriodOver);
        let vr = &mut ctx.accounts.vote_record;
        require!(!vr.voted, ErrorCode::AlreadyVoted);
        vr.voter = ctx.accounts.voter.key();
        vr.proposal = ctx.accounts.proposal.key();
        vr.in_favor = in_favor;
        vr.weight = weight;
        vr.voted = true;
        if in_favor {{ p.votes_for = p.votes_for.checked_add(weight).ok_or(ErrorCode::Overflow)?; }}
        else {{ p.votes_against = p.votes_against.checked_add(weight).ok_or(ErrorCode::Overflow)?; }}
        emit!(VoteCast {{ proposal_id: p.proposal_id, voter: ctx.accounts.voter.key(), in_favor, weight }});
        Ok(())
    }}

    pub fn execute_proposal(ctx: Context<ExecuteProposal>) -> Result<()> {{
        let clock = Clock::get()?;
        let p = &mut ctx.accounts.proposal;
        require!(!p.executed, ErrorCode::AlreadyExecuted);
        require!(clock.unix_timestamp >= p.ends_at, ErrorCode::VotingPeriodNotOver);
        require!(p.votes_for >= ctx.accounts.dao.quorum, ErrorCode::QuorumNotMet);
        require!(p.votes_for > p.votes_against, ErrorCode::ProposalDefeated);
        p.executed = true;
        emit!(ProposalExecuted {{ proposal_id: p.proposal_id }});
        Ok(())
    }}
}}

#[derive(Accounts)]
pub struct InitializeDao<\'info> {{
    #[account(init, payer = authority, space = 8 + DaoConfig::INIT_SPACE, seeds = [b"dao"], bump)]
    pub dao: Account<\'info, DaoConfig>,
    #[account(mut)] pub authority: Signer<\'info>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
#[instruction(proposal_id: u64)]
pub struct CreateProposal<\'info> {{
    #[account(mut, seeds = [b"dao"], bump = dao.bump)] pub dao: Account<\'info, DaoConfig>,
    #[account(init, payer = proposer, space = 8 + Proposal::INIT_SPACE,
        seeds = [b"proposal", &proposal_id.to_le_bytes()], bump)]
    pub proposal: Account<\'info, Proposal>,
    #[account(mut)] pub proposer: Signer<\'info>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
pub struct CastVote<\'info> {{
    #[account(seeds = [b"dao"], bump = dao.bump)] pub dao: Account<\'info, DaoConfig>,
    #[account(mut, seeds = [b"proposal", &proposal.proposal_id.to_le_bytes()], bump)]
    pub proposal: Account<\'info, Proposal>,
    #[account(init, payer = voter, space = 8 + VoteRecord::INIT_SPACE,
        seeds = [b"vote", proposal.key().as_ref(), voter.key().as_ref()], bump)]
    pub vote_record: Account<\'info, VoteRecord>,
    #[account(mut)] pub voter: Signer<\'info>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
pub struct ExecuteProposal<\'info> {{
    #[account(seeds = [b"dao"], bump = dao.bump)] pub dao: Account<\'info, DaoConfig>,
    #[account(mut, seeds = [b"proposal", &proposal.proposal_id.to_le_bytes()], bump)]
    pub proposal: Account<\'info, Proposal>,
    #[account(mut)] pub authority: Signer<\'info>,
}}

#[account]
#[derive(InitSpace)]
pub struct DaoConfig {{
    pub authority: Pubkey, pub gov_mint: Pubkey,
    pub quorum: u64, pub voting_period: i64,
    pub proposal_count: u64, pub bump: u8,
}}

#[account]
#[derive(InitSpace)]
pub struct Proposal {{
    pub dao: Pubkey, pub proposer: Pubkey, pub proposal_id: u64,
    #[max_len(100)] pub title: String,
    #[max_len(500)] pub description: String,
    pub votes_for: u64, pub votes_against: u64,
    pub created_at: i64, pub ends_at: i64,
    pub executed: bool, pub cancelled: bool,
}}

#[account]
#[derive(InitSpace)]
pub struct VoteRecord {{
    pub voter: Pubkey, pub proposal: Pubkey,
    pub in_favor: bool, pub weight: u64, pub voted: bool,
}}

#[event] pub struct DaoInitialized {{ pub authority: Pubkey, pub quorum: u64, pub voting_period: i64 }}
#[event] pub struct ProposalCreated {{ pub proposal_id: u64, pub proposer: Pubkey, pub title: String, pub ends_at: i64 }}
#[event] pub struct VoteCast {{ pub proposal_id: u64, pub voter: Pubkey, pub in_favor: bool, pub weight: u64 }}
#[event] pub struct ProposalExecuted {{ pub proposal_id: u64 }}

#[error_code]
pub enum ErrorCode {{
    #[msg("Proposal is not active")]            ProposalNotActive,
    #[msg("Already voted on this proposal")]    AlreadyVoted,
    #[msg("Quorum not reached")]                QuorumNotMet,
    #[msg("Voting period is over")]             VotingPeriodOver,
    #[msg("Voting period not over yet")]        VotingPeriodNotOver,
    #[msg("Proposal already executed")]         AlreadyExecuted,
    #[msg("Proposal defeated (more against votes)")] ProposalDefeated,
    #[msg("Title exceeds max length")]          TitleTooLong,
    #[msg("Description exceeds max length")]    DescriptionTooLong,
    #[msg("Vote weight must be greater than 0")] ZeroWeight,
    #[msg("Arithmetic overflow")]               Overflow,
}}
'''


def LOTTERY_TEMPLATE(program_name: str) -> str:
    mod = to_rust_name(program_name)
    return f'''// Generated by AnchorScaffold — LixerDev
// Template: On-Chain Lottery | Program: {program_name}

use anchor_lang::prelude::*;

declare_id!("11111111111111111111111111111111");

#[program]
pub mod {mod} {{
    use super::*;

    pub fn initialize_lottery(ctx: Context<InitializeLottery>, lottery_id: u64, ticket_price: u64, end_time: i64, max_tickets: u32) -> Result<()> {{
        require!(ticket_price > 0, ErrorCode::ZeroAmount);
        let l = &mut ctx.accounts.lottery;
        l.authority = ctx.accounts.authority.key();
        l.lottery_id = lottery_id;
        l.ticket_price = ticket_price;
        l.end_time = end_time;
        l.max_tickets = max_tickets;
        l.total_tickets = 0;
        l.winner = None;
        l.prize_claimed = false;
        l.bump = ctx.bumps.lottery;
        emit!(LotteryInitialized {{ lottery_id, ticket_price, end_time }});
        Ok(())
    }}

    pub fn buy_ticket(ctx: Context<BuyTicket>) -> Result<()> {{
        let clock = Clock::get()?;
        let l = &ctx.accounts.lottery;
        require!(clock.unix_timestamp < l.end_time, ErrorCode::LotteryEnded);
        require!(l.winner.is_none(), ErrorCode::LotteryDrawn);
        require!(l.total_tickets < l.max_tickets, ErrorCode::LotteryFull);

        let ticket = &mut ctx.accounts.ticket;
        ticket.owner = ctx.accounts.buyer.key();
        ticket.lottery = ctx.accounts.lottery.key();
        ticket.ticket_number = ctx.accounts.lottery.total_tickets;
        ticket.purchased_at = clock.unix_timestamp;

        // Transfer SOL to lottery vault (using lamport transfer)
        let ix = anchor_lang::solana_program::system_instruction::transfer(
            &ctx.accounts.buyer.key(),
            &ctx.accounts.lottery.key(),
            l.ticket_price,
        );
        anchor_lang::solana_program::program::invoke(
            &ix,
            &[ctx.accounts.buyer.to_account_info(), ctx.accounts.lottery.to_account_info()],
        )?;

        ctx.accounts.lottery.total_tickets = ctx.accounts.lottery.total_tickets.checked_add(1).ok_or(ErrorCode::Overflow)?;
        emit!(TicketPurchased {{ lottery_id: l.lottery_id, buyer: ctx.accounts.buyer.key(), ticket_number: ticket.ticket_number }});
        Ok(())
    }}

    pub fn draw_winner(ctx: Context<DrawWinner>) -> Result<()> {{
        let clock = Clock::get()?;
        let l = &mut ctx.accounts.lottery;
        require!(clock.unix_timestamp >= l.end_time, ErrorCode::LotteryNotEnded);
        require!(l.winner.is_none(), ErrorCode::AlreadyDrawn);
        require!(l.total_tickets > 0, ErrorCode::NoTickets);

        // Use recent slot hash as pseudo-randomness (for prod use Switchboard VRF)
        let recent_slothash = ctx.accounts.slot_hashes.data.borrow();
        let most_recent = arrayref::array_ref![recent_slothash, 12, 8];
        let random_num = u64::from_le_bytes(*most_recent);
        let winner_idx = (random_num % l.total_tickets as u64) as u32;

        l.winner = Some(winner_idx);
        emit!(WinnerDrawn {{ lottery_id: l.lottery_id, winner_ticket: winner_idx }});
        Ok(())
    }}
}}

#[derive(Accounts)]
#[instruction(lottery_id: u64)]
pub struct InitializeLottery<\'info> {{
    #[account(init, payer = authority, space = 8 + LotteryAccount::INIT_SPACE,
        seeds = [b"lottery", &lottery_id.to_le_bytes()], bump)]
    pub lottery: Account<\'info, LotteryAccount>,
    #[account(mut)] pub authority: Signer<\'info>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
pub struct BuyTicket<\'info> {{
    #[account(mut, seeds = [b"lottery", &lottery.lottery_id.to_le_bytes()], bump = lottery.bump)]
    pub lottery: Account<\'info, LotteryAccount>,
    #[account(init, payer = buyer, space = 8 + TicketAccount::INIT_SPACE,
        seeds = [b"ticket", lottery.key().as_ref(), buyer.key().as_ref()], bump)]
    pub ticket: Account<\'info, TicketAccount>,
    #[account(mut)] pub buyer: Signer<\'info>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
pub struct DrawWinner<\'info> {{
    #[account(mut, seeds = [b"lottery", &lottery.lottery_id.to_le_bytes()], bump = lottery.bump, has_one = authority)]
    pub lottery: Account<\'info, LotteryAccount>,
    /// CHECK: SlotHashes sysvar — read-only
    pub slot_hashes: UncheckedAccount<\'info>,
    pub authority: Signer<\'info>,
}}

#[account]
#[derive(InitSpace)]
pub struct LotteryAccount {{
    pub authority: Pubkey, pub lottery_id: u64, pub ticket_price: u64,
    pub end_time: i64, pub max_tickets: u32, pub total_tickets: u32,
    pub winner: Option<u32>, pub prize_claimed: bool, pub bump: u8,
}}

#[account]
#[derive(InitSpace)]
pub struct TicketAccount {{
    pub owner: Pubkey, pub lottery: Pubkey,
    pub ticket_number: u32, pub purchased_at: i64,
}}

#[event] pub struct LotteryInitialized {{ pub lottery_id: u64, pub ticket_price: u64, pub end_time: i64 }}
#[event] pub struct TicketPurchased {{ pub lottery_id: u64, pub buyer: Pubkey, pub ticket_number: u32 }}
#[event] pub struct WinnerDrawn {{ pub lottery_id: u64, pub winner_ticket: u32 }}

#[error_code]
pub enum ErrorCode {{
    #[msg("Lottery has ended")]          LotteryEnded,
    #[msg("Winner already drawn")]       AlreadyDrawn,
    #[msg("Lottery not ended yet")]      LotteryNotEnded,
    #[msg("Winner already drawn")]       LotteryDrawn,
    #[msg("Lottery is full")]            LotteryFull,
    #[msg("No tickets sold")]            NoTickets,
    #[msg("Amount must be > 0")]         ZeroAmount,
    #[msg("Arithmetic overflow")]        Overflow,
}}
'''


def MULTISIG_TEMPLATE(program_name: str) -> str:
    mod = to_rust_name(program_name)
    return f'''// Generated by AnchorScaffold — LixerDev
// Template: M-of-N Multisig | Program: {program_name}

use anchor_lang::prelude::*;

declare_id!("11111111111111111111111111111111");

const MAX_OWNERS: usize = 10;

#[program]
pub mod {mod} {{
    use super::*;

    pub fn create_multisig(ctx: Context<CreateMultisig>, owners: Vec<Pubkey>, threshold: u8) -> Result<()> {{
        require!(owners.len() >= threshold as usize, ErrorCode::ThresholdTooHigh);
        require!(owners.len() <= MAX_OWNERS, ErrorCode::TooManyOwners);
        require!(threshold >= 1, ErrorCode::InvalidThreshold);
        let ms = &mut ctx.accounts.multisig;
        ms.owners = owners;
        ms.threshold = threshold;
        ms.transaction_count = 0;
        ms.bump = ctx.bumps.multisig;
        ms.creator = ctx.accounts.creator.key();
        Ok(())
    }}

    pub fn create_transaction(ctx: Context<CreateTransaction>, tx_id: u64, to: Pubkey, lamports: u64) -> Result<()> {{
        require!(is_owner(&ctx.accounts.multisig.owners, &ctx.accounts.proposer.key()), ErrorCode::NotOwner);
        let tx = &mut ctx.accounts.transaction;
        tx.multisig = ctx.accounts.multisig.key();
        tx.proposer = ctx.accounts.proposer.key();
        tx.to = to;
        tx.lamports = lamports;
        tx.tx_id = tx_id;
        tx.approvals = 1;
        tx.rejections = 0;
        tx.executed = false;
        tx.approved_by = vec![ctx.accounts.proposer.key()];
        tx.created_at = Clock::get()?.unix_timestamp;
        ctx.accounts.multisig.transaction_count = ctx.accounts.multisig.transaction_count.checked_add(1).ok_or(ErrorCode::Overflow)?;
        emit!(TransactionCreated {{ tx_id, proposer: tx.proposer, to, lamports }});
        Ok(())
    }}

    pub fn approve(ctx: Context<Approve>, _tx_id: u64) -> Result<()> {{
        let ms = &ctx.accounts.multisig;
        require!(is_owner(&ms.owners, &ctx.accounts.approver.key()), ErrorCode::NotOwner);
        let tx = &mut ctx.accounts.transaction;
        require!(!tx.executed, ErrorCode::AlreadyExecuted);
        require!(!tx.approved_by.contains(&ctx.accounts.approver.key()), ErrorCode::AlreadyApproved);
        tx.approved_by.push(ctx.accounts.approver.key());
        tx.approvals = tx.approvals.checked_add(1).ok_or(ErrorCode::Overflow)?;
        emit!(TransactionApproved {{ tx_id: tx.tx_id, approver: ctx.accounts.approver.key(), approvals: tx.approvals }});
        Ok(())
    }}

    pub fn execute_transaction(ctx: Context<ExecuteTransaction>, _tx_id: u64) -> Result<()> {{
        let ms = &ctx.accounts.multisig;
        let tx = &mut ctx.accounts.transaction;
        require!(!tx.executed, ErrorCode::AlreadyExecuted);
        require!(tx.approvals >= ms.threshold, ErrorCode::ThresholdNotMet);
        tx.executed = true;
        // Transfer lamports from multisig to `to`
        **ctx.accounts.multisig.to_account_info().try_borrow_mut_lamports()? -= tx.lamports;
        **ctx.accounts.to.try_borrow_mut_lamports()? += tx.lamports;
        emit!(TransactionExecuted {{ tx_id: tx.tx_id, to: tx.to, lamports: tx.lamports }});
        Ok(())
    }}
}}

fn is_owner(owners: &[Pubkey], key: &Pubkey) -> bool {{ owners.contains(key) }}

#[derive(Accounts)]
pub struct CreateMultisig<\'info> {{
    #[account(init, payer = creator, space = 8 + Multisig::INIT_SPACE,
        seeds = [b"multisig", creator.key().as_ref()], bump)]
    pub multisig: Account<\'info, Multisig>,
    #[account(mut)] pub creator: Signer<\'info>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
#[instruction(tx_id: u64)]
pub struct CreateTransaction<\'info> {{
    #[account(mut, seeds = [b"multisig", multisig.creator.as_ref()], bump = multisig.bump)]
    pub multisig: Account<\'info, Multisig>,
    #[account(init, payer = proposer, space = 8 + MultisigTransaction::INIT_SPACE,
        seeds = [b"tx", multisig.key().as_ref(), &tx_id.to_le_bytes()], bump)]
    pub transaction: Account<\'info, MultisigTransaction>,
    #[account(mut)] pub proposer: Signer<\'info>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
#[instruction(tx_id: u64)]
pub struct Approve<\'info> {{
    #[account(seeds = [b"multisig", multisig.creator.as_ref()], bump = multisig.bump)]
    pub multisig: Account<\'info, Multisig>,
    #[account(mut, seeds = [b"tx", multisig.key().as_ref(), &tx_id.to_le_bytes()], bump)]
    pub transaction: Account<\'info, MultisigTransaction>,
    pub approver: Signer<\'info>,
}}

#[derive(Accounts)]
#[instruction(tx_id: u64)]
pub struct ExecuteTransaction<\'info> {{
    #[account(mut, seeds = [b"multisig", multisig.creator.as_ref()], bump = multisig.bump)]
    pub multisig: Account<\'info, Multisig>,
    #[account(mut, seeds = [b"tx", multisig.key().as_ref(), &tx_id.to_le_bytes()], bump)]
    pub transaction: Account<\'info, MultisigTransaction>,
    /// CHECK: destination for lamports
    #[account(mut)] pub to: UncheckedAccount<\'info>,
    pub authority: Signer<\'info>,
}}

#[account]
#[derive(InitSpace)]
pub struct Multisig {{
    pub creator: Pubkey,
    #[max_len(10)] pub owners: Vec<Pubkey>,
    pub threshold: u8, pub transaction_count: u64, pub bump: u8,
}}

#[account]
#[derive(InitSpace)]
pub struct MultisigTransaction {{
    pub multisig: Pubkey, pub proposer: Pubkey, pub to: Pubkey,
    pub lamports: u64, pub tx_id: u64, pub approvals: u8, pub rejections: u8,
    pub executed: bool, pub created_at: i64,
    #[max_len(10)] pub approved_by: Vec<Pubkey>,
}}

#[event] pub struct TransactionCreated {{ pub tx_id: u64, pub proposer: Pubkey, pub to: Pubkey, pub lamports: u64 }}
#[event] pub struct TransactionApproved {{ pub tx_id: u64, pub approver: Pubkey, pub approvals: u8 }}
#[event] pub struct TransactionExecuted {{ pub tx_id: u64, pub to: Pubkey, pub lamports: u64 }}

#[error_code]
pub enum ErrorCode {{
    #[msg("Not an owner of this multisig")]    NotOwner,
    #[msg("Already approved")]                 AlreadyApproved,
    #[msg("Transaction already executed")]     AlreadyExecuted,
    #[msg("Threshold not met")]                ThresholdNotMet,
    #[msg("Threshold cannot exceed owner count")] ThresholdTooHigh,
    #[msg("Too many owners (max 10)")]         TooManyOwners,
    #[msg("Threshold must be at least 1")]     InvalidThreshold,
    #[msg("Arithmetic overflow")]              Overflow,
}}
'''


def MARKETPLACE_TEMPLATE(program_name: str) -> str:
    mod = to_rust_name(program_name)
    return f'''// Generated by AnchorScaffold — LixerDev
// Template: NFT Marketplace | Program: {program_name}

use anchor_lang::prelude::*;
use anchor_spl::token::{{self, Token, TokenAccount, Mint, Transfer}};

declare_id!("11111111111111111111111111111111");

#[program]
pub mod {mod} {{
    use super::*;

    pub fn initialize_marketplace(ctx: Context<InitializeMarketplace>, fee_bps: u16) -> Result<()> {{
        require!(fee_bps <= 1000, ErrorCode::FeeTooHigh); // max 10%
        let mp = &mut ctx.accounts.marketplace;
        mp.authority = ctx.accounts.authority.key();
        mp.fee_bps = fee_bps;
        mp.total_volume = 0;
        mp.bump = ctx.bumps.marketplace;
        Ok(())
    }}

    pub fn list_nft(ctx: Context<ListNft>, price: u64) -> Result<()> {{
        require!(price > 0, ErrorCode::ZeroPrice);
        let listing = &mut ctx.accounts.listing;
        listing.seller = ctx.accounts.seller.key();
        listing.nft_mint = ctx.accounts.nft_mint.key();
        listing.price = price;
        listing.active = true;
        listing.listed_at = Clock::get()?.unix_timestamp;
        listing.bump = ctx.bumps.listing;

        // Transfer NFT to escrow vault
        token::transfer(
            CpiContext::new(
                ctx.accounts.token_program.to_account_info(),
                Transfer {{
                    from: ctx.accounts.seller_nft_ata.to_account_info(),
                    to: ctx.accounts.vault.to_account_info(),
                    authority: ctx.accounts.seller.to_account_info(),
                }},
            ),
            1,
        )?;
        emit!(NftListed {{ mint: listing.nft_mint, seller: listing.seller, price }});
        Ok(())
    }}

    pub fn buy_nft(ctx: Context<BuyNft>) -> Result<()> {{
        let listing = &ctx.accounts.listing;
        require!(listing.active, ErrorCode::ListingNotActive);
        let price = listing.price;
        let fee = price.checked_mul(ctx.accounts.marketplace.fee_bps as u64).ok_or(ErrorCode::Overflow)?
            .checked_div(10_000).ok_or(ErrorCode::Overflow)?;
        let seller_proceeds = price.checked_sub(fee).ok_or(ErrorCode::Underflow)?;

        // Transfer SOL: buyer → seller
        let transfer_to_seller = anchor_lang::solana_program::system_instruction::transfer(
            &ctx.accounts.buyer.key(), &ctx.accounts.seller.key(), seller_proceeds,
        );
        anchor_lang::solana_program::program::invoke(
            &transfer_to_seller,
            &[ctx.accounts.buyer.to_account_info(), ctx.accounts.seller.to_account_info()],
        )?;

        // Transfer SOL: buyer → authority (fee)
        if fee > 0 {{
            let transfer_fee = anchor_lang::solana_program::system_instruction::transfer(
                &ctx.accounts.buyer.key(), &ctx.accounts.marketplace.authority, fee,
            );
            anchor_lang::solana_program::program::invoke(
                &transfer_fee,
                &[ctx.accounts.buyer.to_account_info(), ctx.accounts.fee_receiver.to_account_info()],
            )?;
        }}

        // Transfer NFT from vault to buyer
        let nft_mint_key = listing.nft_mint;
        let seeds: &[&[u8]] = &[b"listing", nft_mint_key.as_ref(), &[listing.bump]];
        let signer = &[seeds];
        token::transfer(
            CpiContext::new_with_signer(
                ctx.accounts.token_program.to_account_info(),
                Transfer {{
                    from: ctx.accounts.vault.to_account_info(),
                    to: ctx.accounts.buyer_nft_ata.to_account_info(),
                    authority: ctx.accounts.listing.to_account_info(),
                }},
                signer,
            ),
            1,
        )?;

        ctx.accounts.listing.active = false;
        ctx.accounts.marketplace.total_volume = ctx.accounts.marketplace.total_volume.checked_add(price).ok_or(ErrorCode::Overflow)?;
        emit!(NftSold {{ mint: nft_mint_key, buyer: ctx.accounts.buyer.key(), seller: ctx.accounts.seller.key(), price }});
        Ok(())
    }}
}}

#[derive(Accounts)]
pub struct InitializeMarketplace<\'info> {{
    #[account(init, payer = authority, space = 8 + MarketplaceConfig::INIT_SPACE, seeds = [b"marketplace"], bump)]
    pub marketplace: Account<\'info, MarketplaceConfig>,
    #[account(mut)] pub authority: Signer<\'info>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
pub struct ListNft<\'info> {{
    #[account(seeds = [b"marketplace"], bump = marketplace.bump)] pub marketplace: Account<\'info, MarketplaceConfig>,
    #[account(init, payer = seller, space = 8 + Listing::INIT_SPACE, seeds = [b"listing", nft_mint.key().as_ref()], bump)]
    pub listing: Account<\'info, Listing>,
    #[account(init, payer = seller, token::mint = nft_mint, token::authority = listing, seeds = [b"vault", nft_mint.key().as_ref()], bump)]
    pub vault: Account<\'info, TokenAccount>,
    pub nft_mint: Account<\'info, Mint>,
    #[account(mut, token::mint = nft_mint, token::authority = seller)] pub seller_nft_ata: Account<\'info, TokenAccount>,
    #[account(mut)] pub seller: Signer<\'info>,
    pub token_program: Program<\'info, Token>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
pub struct BuyNft<\'info> {{
    #[account(mut, seeds = [b"marketplace"], bump = marketplace.bump)] pub marketplace: Account<\'info, MarketplaceConfig>,
    #[account(mut, seeds = [b"listing", listing.nft_mint.as_ref()], bump = listing.bump)] pub listing: Account<\'info, Listing>,
    #[account(mut, seeds = [b"vault", listing.nft_mint.as_ref()], bump)] pub vault: Account<\'info, TokenAccount>,
    #[account(mut, token::mint = listing.nft_mint)] pub buyer_nft_ata: Account<\'info, TokenAccount>,
    /// CHECK: seller — receives proceeds
    #[account(mut, address = listing.seller)] pub seller: UncheckedAccount<\'info>,
    /// CHECK: fee receiver — marketplace authority
    #[account(mut, address = marketplace.authority)] pub fee_receiver: UncheckedAccount<\'info>,
    #[account(mut)] pub buyer: Signer<\'info>,
    pub token_program: Program<\'info, Token>,
    pub system_program: Program<\'info, System>,
}}

#[account]
#[derive(InitSpace)]
pub struct MarketplaceConfig {{
    pub authority: Pubkey, pub fee_bps: u16, pub total_volume: u64, pub bump: u8,
}}

#[account]
#[derive(InitSpace)]
pub struct Listing {{
    pub seller: Pubkey, pub nft_mint: Pubkey,
    pub price: u64, pub listed_at: i64, pub active: bool, pub bump: u8,
}}

#[event] pub struct NftListed {{ pub mint: Pubkey, pub seller: Pubkey, pub price: u64 }}
#[event] pub struct NftSold {{ pub mint: Pubkey, pub buyer: Pubkey, pub seller: Pubkey, pub price: u64 }}
#[event] pub struct NftDelisted {{ pub mint: Pubkey, pub seller: Pubkey }}

#[error_code]
pub enum ErrorCode {{
    #[msg("Listing is not active")]          ListingNotActive,
    #[msg("Price must be greater than zero")] ZeroPrice,
    #[msg("Fee cannot exceed 10%")]          FeeTooHigh,
    #[msg("Arithmetic overflow")]            Overflow,
    #[msg("Arithmetic underflow")]           Underflow,
}}
'''


def LAUNCHPAD_TEMPLATE(program_name: str) -> str:
    mod = to_rust_name(program_name)
    return f'''// Generated by AnchorScaffold — LixerDev
// Template: Token Launchpad (Fair Launch) | Program: {program_name}

use anchor_lang::prelude::*;
use anchor_spl::token::{{self, Token, TokenAccount, Mint, Transfer}};

declare_id!("11111111111111111111111111111111");

#[program]
pub mod {mod} {{
    use super::*;

    pub fn initialize_sale(
        ctx: Context<InitializeSale>,
        sale_id: u64,
        start_time: i64,
        end_time: i64,
        soft_cap: u64,
        hard_cap: u64,
        min_contribution: u64,
        max_contribution: u64,
    ) -> Result<()> {{
        require!(end_time > start_time, ErrorCode::InvalidTimestamps);
        require!(hard_cap >= soft_cap && soft_cap > 0, ErrorCode::InvalidCaps);
        require!(max_contribution >= min_contribution && min_contribution > 0, ErrorCode::InvalidContributionLimits);

        let sale = &mut ctx.accounts.sale;
        sale.authority = ctx.accounts.authority.key();
        sale.token_mint = ctx.accounts.token_mint.key();
        sale.sale_id = sale_id;
        sale.start_time = start_time;
        sale.end_time = end_time;
        sale.soft_cap = soft_cap;
        sale.hard_cap = hard_cap;
        sale.min_contribution = min_contribution;
        sale.max_contribution = max_contribution;
        sale.total_raised = 0;
        sale.total_tokens = 0;
        sale.finalized = false;
        sale.bump = ctx.bumps.sale;

        emit!(SaleInitialized {{ sale_id, start_time, end_time, hard_cap }});
        Ok(())
    }}

    pub fn contribute(ctx: Context<Contribute>, amount: u64) -> Result<()> {{
        let sale = &ctx.accounts.sale;
        let clock = Clock::get()?;
        require!(clock.unix_timestamp >= sale.start_time, ErrorCode::SaleNotStarted);
        require!(clock.unix_timestamp < sale.end_time, ErrorCode::SaleEnded);
        require!(!sale.finalized, ErrorCode::SaleFinalized);
        require!(amount >= sale.min_contribution, ErrorCode::BelowMinContribution);

        let contrib = &ctx.accounts.contribution;
        let new_total = contrib.amount.checked_add(amount).ok_or(ErrorCode::Overflow)?;
        require!(new_total <= sale.max_contribution, ErrorCode::ExceedsMaxContribution);
        require!(
            sale.total_raised.checked_add(amount).ok_or(ErrorCode::Overflow)? <= sale.hard_cap,
            ErrorCode::HardCapReached
        );

        // Transfer SOL to sale vault
        let ix = anchor_lang::solana_program::system_instruction::transfer(
            &ctx.accounts.contributor.key(), &ctx.accounts.sale.key(), amount,
        );
        anchor_lang::solana_program::program::invoke(
            &ix,
            &[ctx.accounts.contributor.to_account_info(), ctx.accounts.sale.to_account_info()],
        )?;

        let contrib = &mut ctx.accounts.contribution;
        contrib.contributor = ctx.accounts.contributor.key();
        contrib.sale = ctx.accounts.sale.key();
        contrib.amount = contrib.amount.checked_add(amount).ok_or(ErrorCode::Overflow)?;

        ctx.accounts.sale.total_raised = ctx.accounts.sale.total_raised.checked_add(amount).ok_or(ErrorCode::Overflow)?;

        emit!(ContributionMade {{ sale_id: sale.sale_id, contributor: contrib.contributor, amount }});
        Ok(())
    }}

    pub fn finalize_sale(ctx: Context<FinalizeSale>) -> Result<()> {{
        let sale = &mut ctx.accounts.sale;
        let clock = Clock::get()?;
        require!(clock.unix_timestamp >= sale.end_time, ErrorCode::SaleNotEnded);
        require!(!sale.finalized, ErrorCode::SaleFinalized);
        require!(sale.total_raised >= sale.soft_cap, ErrorCode::SoftCapNotMet);
        sale.finalized = true;
        // Deposit project tokens into vault (authority must call this with tokens)
        token::transfer(
            CpiContext::new(
                ctx.accounts.token_program.to_account_info(),
                Transfer {{
                    from: ctx.accounts.authority_token_ata.to_account_info(),
                    to: ctx.accounts.token_vault.to_account_info(),
                    authority: ctx.accounts.authority.to_account_info(),
                }},
            ),
            ctx.accounts.authority_token_ata.amount, // deposit all tokens
        )?;
        sale.total_tokens = ctx.accounts.token_vault.amount;
        emit!(SaleFinalized {{ sale_id: sale.sale_id, total_raised: sale.total_raised }});
        Ok(())
    }}
}}

#[derive(Accounts)]
#[instruction(sale_id: u64)]
pub struct InitializeSale<\'info> {{
    #[account(init, payer = authority, space = 8 + SaleConfig::INIT_SPACE,
        seeds = [b"sale", &sale_id.to_le_bytes()], bump)]
    pub sale: Account<\'info, SaleConfig>,
    pub token_mint: Account<\'info, Mint>,
    #[account(mut)] pub authority: Signer<\'info>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
pub struct Contribute<\'info> {{
    #[account(mut, seeds = [b"sale", &sale.sale_id.to_le_bytes()], bump = sale.bump)]
    pub sale: Account<\'info, SaleConfig>,
    #[account(init_if_needed, payer = contributor, space = 8 + Contribution::INIT_SPACE,
        seeds = [b"contribution", sale.key().as_ref(), contributor.key().as_ref()], bump)]
    pub contribution: Account<\'info, Contribution>,
    #[account(mut)] pub contributor: Signer<\'info>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
pub struct FinalizeSale<\'info> {{
    #[account(mut, seeds = [b"sale", &sale.sale_id.to_le_bytes()], bump = sale.bump, has_one = authority)]
    pub sale: Account<\'info, SaleConfig>,
    #[account(init_if_needed, payer = authority, token::mint = sale.token_mint, token::authority = sale,
        seeds = [b"token_vault", &sale.sale_id.to_le_bytes()], bump)]
    pub token_vault: Account<\'info, TokenAccount>,
    #[account(mut, token::mint = sale.token_mint, token::authority = authority)]
    pub authority_token_ata: Account<\'info, TokenAccount>,
    #[account(mut)] pub authority: Signer<\'info>,
    pub token_program: Program<\'info, Token>,
    pub system_program: Program<\'info, System>,
}}

#[account]
#[derive(InitSpace)]
pub struct SaleConfig {{
    pub authority: Pubkey, pub token_mint: Pubkey,
    pub sale_id: u64, pub start_time: i64, pub end_time: i64,
    pub soft_cap: u64, pub hard_cap: u64, pub total_raised: u64, pub total_tokens: u64,
    pub min_contribution: u64, pub max_contribution: u64,
    pub finalized: bool, pub bump: u8,
}}

#[account]
#[derive(InitSpace)]
pub struct Contribution {{
    pub contributor: Pubkey, pub sale: Pubkey, pub amount: u64, pub claimed: bool,
}}

#[event] pub struct SaleInitialized {{ pub sale_id: u64, pub start_time: i64, pub end_time: i64, pub hard_cap: u64 }}
#[event] pub struct ContributionMade {{ pub sale_id: u64, pub contributor: Pubkey, pub amount: u64 }}
#[event] pub struct SaleFinalized {{ pub sale_id: u64, pub total_raised: u64 }}
#[event] pub struct TokensClaimed {{ pub sale_id: u64, pub contributor: Pubkey, pub amount: u64 }}

#[error_code]
pub enum ErrorCode {{
    #[msg("Sale has not started yet")]               SaleNotStarted,
    #[msg("Sale has ended")]                         SaleEnded,
    #[msg("Sale already finalized")]                 SaleFinalized,
    #[msg("Sale not ended yet")]                     SaleNotEnded,
    #[msg("Soft cap not reached")]                   SoftCapNotMet,
    #[msg("Hard cap reached")]                       HardCapReached,
    #[msg("Below minimum contribution")]             BelowMinContribution,
    #[msg("Exceeds maximum contribution per wallet")] ExceedsMaxContribution,
    #[msg("Invalid start/end timestamps")]           InvalidTimestamps,
    #[msg("Invalid cap settings")]                   InvalidCaps,
    #[msg("Invalid contribution limits")]            InvalidContributionLimits,
    #[msg("Already claimed")]                        AlreadyClaimed,
    #[msg("Arithmetic overflow")]                    Overflow,
}}
'''
