"""Staking template — time-based SPL token staking with reward accumulation."""

from src.parser import to_rust_name


def STAKING_TEMPLATE(program_name: str) -> str:
    mod = to_rust_name(program_name)
    return f'''// Generated by AnchorScaffold — LixerDev
// Template: Time-Based Staking | Program: {program_name}
// Instructions: initialize, stake, unstake, claim_rewards

use anchor_lang::prelude::*;
use anchor_spl::token::{{self, Token, TokenAccount, Mint, Transfer}};

declare_id!("11111111111111111111111111111111");

#[program]
pub mod {mod} {{
    use super::*;

    /// Initialize the staking pool.
    /// `reward_rate` = reward tokens per staked token per second, scaled by 1e9.
    pub fn initialize(
        ctx: Context<Initialize>,
        reward_rate: u64,
    ) -> Result<()> {{
        let pool = &mut ctx.accounts.pool;
        pool.authority = ctx.accounts.authority.key();
        pool.stake_mint = ctx.accounts.stake_mint.key();
        pool.reward_mint = ctx.accounts.reward_mint.key();
        pool.reward_rate = reward_rate;
        pool.total_staked = 0;
        pool.bump = ctx.bumps.pool;
        emit!(PoolInitialized {{
            authority: pool.authority,
            reward_rate,
            timestamp: Clock::get()?.unix_timestamp,
        }});
        Ok(())
    }}

    /// Stake tokens into the pool. Accrues rewards from this moment onward.
    pub fn stake(ctx: Context<Stake>, amount: u64) -> Result<()> {{
        require!(amount > 0, ErrorCode::ZeroAmount);

        // Claim any pending rewards before changing stake amount
        let clock = Clock::get()?;
        accrue_rewards(&mut ctx.accounts.stake_account, &ctx.accounts.pool, clock.unix_timestamp)?;

        // Transfer tokens from user to vault
        token::transfer(
            CpiContext::new(
                ctx.accounts.token_program.to_account_info(),
                Transfer {{
                    from: ctx.accounts.user_stake_ata.to_account_info(),
                    to: ctx.accounts.vault.to_account_info(),
                    authority: ctx.accounts.user.to_account_info(),
                }},
            ),
            amount,
        )?;

        // Update stake account
        let sa = &mut ctx.accounts.stake_account;
        sa.owner = ctx.accounts.user.key();
        sa.staked_amount = sa.staked_amount.checked_add(amount).ok_or(ErrorCode::Overflow)?;
        sa.last_update_ts = clock.unix_timestamp;

        // Update pool totals
        let pool = &mut ctx.accounts.pool;
        pool.total_staked = pool.total_staked.checked_add(amount).ok_or(ErrorCode::Overflow)?;

        emit!(StakeEvent {{
            user: ctx.accounts.user.key(),
            amount,
            total_staked: pool.total_staked,
            timestamp: clock.unix_timestamp,
        }});
        Ok(())
    }}

    /// Unstake tokens. Claims pending rewards first, then returns principal.
    pub fn unstake(ctx: Context<Unstake>, amount: u64) -> Result<()> {{
        let sa = &mut ctx.accounts.stake_account;
        require!(sa.staked_amount >= amount, ErrorCode::InsufficientStake);
        require!(amount > 0, ErrorCode::ZeroAmount);

        // Accrue rewards before changing stake
        let clock = Clock::get()?;
        accrue_rewards(sa, &ctx.accounts.pool, clock.unix_timestamp)?;

        sa.staked_amount = sa.staked_amount.checked_sub(amount).ok_or(ErrorCode::Underflow)?;
        sa.last_update_ts = clock.unix_timestamp;

        let pool = &mut ctx.accounts.pool;
        pool.total_staked = pool.total_staked.checked_sub(amount).ok_or(ErrorCode::Underflow)?;

        // Return principal from vault
        let seeds = &[b"pool".as_ref(), &[pool.bump]];
        let signer = &[&seeds[..]];
        token::transfer(
            CpiContext::new_with_signer(
                ctx.accounts.token_program.to_account_info(),
                Transfer {{
                    from: ctx.accounts.vault.to_account_info(),
                    to: ctx.accounts.user_stake_ata.to_account_info(),
                    authority: ctx.accounts.pool.to_account_info(),
                }},
                signer,
            ),
            amount,
        )?;

        emit!(UnstakeEvent {{
            user: ctx.accounts.user.key(),
            amount,
            timestamp: clock.unix_timestamp,
        }});
        Ok(())
    }}

    /// Claim all pending rewards without unstaking principal.
    pub fn claim_rewards(ctx: Context<ClaimRewards>) -> Result<()> {{
        let clock = Clock::get()?;
        accrue_rewards(&mut ctx.accounts.stake_account, &ctx.accounts.pool, clock.unix_timestamp)?;

        let sa = &mut ctx.accounts.stake_account;
        let rewards = sa.pending_rewards;
        require!(rewards > 0, ErrorCode::NoPendingRewards);
        sa.pending_rewards = 0;
        sa.total_claimed = sa.total_claimed.checked_add(rewards).ok_or(ErrorCode::Overflow)?;

        // Transfer rewards from reward vault to user
        let pool = &ctx.accounts.pool;
        let seeds = &[b"pool".as_ref(), &[pool.bump]];
        let signer = &[&seeds[..]];
        token::transfer(
            CpiContext::new_with_signer(
                ctx.accounts.token_program.to_account_info(),
                Transfer {{
                    from: ctx.accounts.reward_vault.to_account_info(),
                    to: ctx.accounts.user_reward_ata.to_account_info(),
                    authority: ctx.accounts.pool.to_account_info(),
                }},
                signer,
            ),
            rewards,
        )?;

        emit!(ClaimEvent {{
            user: ctx.accounts.user.key(),
            rewards,
            timestamp: clock.unix_timestamp,
        }});
        Ok(())
    }}
}}

/// Accrue pending rewards for a stake account based on elapsed time.
fn accrue_rewards(
    sa: &mut StakeAccount,
    pool: &StakingPool,
    now: i64,
) -> Result<()> {{
    if sa.staked_amount > 0 && now > sa.last_update_ts {{
        let elapsed = (now - sa.last_update_ts) as u64;
        // rewards = staked * rate * elapsed / 1e9
        let new_rewards = sa.staked_amount
            .checked_mul(pool.reward_rate).ok_or(ErrorCode::Overflow)?
            .checked_mul(elapsed).ok_or(ErrorCode::Overflow)?
            .checked_div(1_000_000_000).ok_or(ErrorCode::Overflow)?;
        sa.pending_rewards = sa.pending_rewards.checked_add(new_rewards).ok_or(ErrorCode::Overflow)?;
    }}
    sa.last_update_ts = now;
    Ok(())
}}

// ─── Account Contexts ───────────────────────────────────────────────────────

#[derive(Accounts)]
pub struct Initialize<\'info> {{
    #[account(
        init,
        payer = authority,
        space = 8 + StakingPool::INIT_SPACE,
        seeds = [b"pool"],
        bump,
    )]
    pub pool: Account<\'info, StakingPool>,

    pub stake_mint:  Account<\'info, Mint>,
    pub reward_mint: Account<\'info, Mint>,

    #[account(
        init,
        payer = authority,
        token::mint = stake_mint,
        token::authority = pool,
        seeds = [b"vault"],
        bump,
    )]
    pub vault: Account<\'info, TokenAccount>,

    #[account(
        init,
        payer = authority,
        token::mint = reward_mint,
        token::authority = pool,
        seeds = [b"reward_vault"],
        bump,
    )]
    pub reward_vault: Account<\'info, TokenAccount>,

    #[account(mut)]
    pub authority: Signer<\'info>,

    pub token_program:  Program<\'info, Token>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
pub struct Stake<\'info> {{
    #[account(mut, seeds = [b"pool"], bump = pool.bump)]
    pub pool: Account<\'info, StakingPool>,

    #[account(
        init_if_needed,
        payer = user,
        space = 8 + StakeAccount::INIT_SPACE,
        seeds = [b"stake", user.key().as_ref()],
        bump,
    )]
    pub stake_account: Account<\'info, StakeAccount>,

    #[account(mut, seeds = [b"vault"], bump)]
    pub vault: Account<\'info, TokenAccount>,

    #[account(mut, token::mint = pool.stake_mint, token::authority = user)]
    pub user_stake_ata: Account<\'info, TokenAccount>,

    #[account(mut)]
    pub user: Signer<\'info>,

    pub token_program:  Program<\'info, Token>,
    pub system_program: Program<\'info, System>,
}}

#[derive(Accounts)]
pub struct Unstake<\'info> {{
    #[account(mut, seeds = [b"pool"], bump = pool.bump)]
    pub pool: Account<\'info, StakingPool>,

    #[account(mut, seeds = [b"stake", user.key().as_ref()], bump)]
    pub stake_account: Account<\'info, StakeAccount>,

    #[account(mut, seeds = [b"vault"], bump)]
    pub vault: Account<\'info, TokenAccount>,

    #[account(mut, token::mint = pool.stake_mint, token::authority = user)]
    pub user_stake_ata: Account<\'info, TokenAccount>,

    #[account(mut)]
    pub user: Signer<\'info>,

    pub token_program: Program<\'info, Token>,
}}

#[derive(Accounts)]
pub struct ClaimRewards<\'info> {{
    #[account(seeds = [b"pool"], bump = pool.bump)]
    pub pool: Account<\'info, StakingPool>,

    #[account(mut, seeds = [b"stake", user.key().as_ref()], bump)]
    pub stake_account: Account<\'info, StakeAccount>,

    #[account(mut, seeds = [b"reward_vault"], bump)]
    pub reward_vault: Account<\'info, TokenAccount>,

    #[account(mut, token::mint = pool.reward_mint, token::authority = user)]
    pub user_reward_ata: Account<\'info, TokenAccount>,

    #[account(mut)]
    pub user: Signer<\'info>,

    pub token_program: Program<\'info, Token>,
}}

// ─── State Accounts ──────────────────────────────────────────────────────────

#[account]
#[derive(InitSpace)]
pub struct StakingPool {{
    pub authority:    Pubkey,  // 32
    pub stake_mint:   Pubkey,  // 32
    pub reward_mint:  Pubkey,  // 32
    pub reward_rate:  u64,     // 8  — tokens/s/staked_token × 1e9
    pub total_staked: u64,     // 8
    pub bump:         u8,      // 1
}}

#[account]
#[derive(InitSpace)]
pub struct StakeAccount {{
    pub owner:          Pubkey,  // 32
    pub staked_amount:  u64,     // 8
    pub pending_rewards: u64,    // 8
    pub total_claimed:  u64,     // 8
    pub last_update_ts: i64,     // 8
}}

// ─── Events ──────────────────────────────────────────────────────────────────

#[event]
pub struct PoolInitialized {{
    pub authority:   Pubkey,
    pub reward_rate: u64,
    pub timestamp:   i64,
}}

#[event]
pub struct StakeEvent {{
    pub user:         Pubkey,
    pub amount:       u64,
    pub total_staked: u64,
    pub timestamp:    i64,
}}

#[event]
pub struct UnstakeEvent {{
    pub user:      Pubkey,
    pub amount:    u64,
    pub timestamp: i64,
}}

#[event]
pub struct ClaimEvent {{
    pub user:      Pubkey,
    pub rewards:   u64,
    pub timestamp: i64,
}}

// ─── Errors ──────────────────────────────────────────────────────────────────

#[error_code]
pub enum ErrorCode {{
    #[msg("Staked amount is less than the requested unstake amount")]
    InsufficientStake,
    #[msg("No pending rewards to claim")]
    NoPendingRewards,
    #[msg("Amount must be greater than zero")]
    ZeroAmount,
    #[msg("Arithmetic overflow")]
    Overflow,
    #[msg("Arithmetic underflow")]
    Underflow,
    #[msg("Unauthorized: only the pool authority can perform this action")]
    Unauthorized,
}}
'''
