"""
Scaffolder — creates the full Anchor project directory structure on disk.
"""

import os
from pathlib import Path
from src.models import GeneratedProgram
from src.parser import to_rust_name
from src.logger import get_logger
from config import config

logger = get_logger(__name__)


def scaffold_project(program: GeneratedProgram, output_dir: str = None) -> str:
    """
    Write a GeneratedProgram to disk as a complete Anchor project.

    Parameters:
    - program: Generated program with all file contents
    - output_dir: Target directory (default: config.OUTPUT_DIR / program.name)

    Returns:
    - str: Path to the created project root
    """
    base = Path(output_dir or config.OUTPUT_DIR) / program.name
    base.mkdir(parents=True, exist_ok=True)

    prog_dir = base / "programs" / program.name / "src"
    prog_dir.mkdir(parents=True, exist_ok=True)

    tests_dir = base / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)

    migrations_dir = base / "migrations"
    migrations_dir.mkdir(parents=True, exist_ok=True)

    app_dir = base / "app"
    app_dir.mkdir(parents=True, exist_ok=True)

    # Write Anchor.toml
    _write(base / "Anchor.toml", program.anchor_toml)

    # Write workspace Cargo.toml
    _write(base / "Cargo.toml", program.cargo_workspace)

    # Write program Cargo.toml
    _write(base / "programs" / program.name / "Cargo.toml", program.cargo_program)

    # Write lib.rs (the main program)
    _write(prog_dir / "lib.rs", program.rust_code)

    # Write TypeScript tests
    _write(tests_dir / f"{program.name}.ts", program.typescript_tests)

    # Write migrations/deploy.ts
    _write(migrations_dir / "deploy.ts", _migrations_stub(program.name))

    # Write app/index.ts client stub
    if config.GENERATE_CLIENT and program.client_stub:
        _write(app_dir / "index.ts", program.client_stub)

    # Write .gitignore
    _write(base / ".gitignore", _gitignore())

    # Write tsconfig.json
    _write(base / "tsconfig.json", _tsconfig())

    # Write package.json
    _write(base / "package.json", _package_json(program.name))

    logger.info(f"Project scaffolded at: {base}")
    return str(base)


def _write(path: Path, content: str):
    path.write_text(content, encoding="utf-8")
    logger.debug(f"Written: {path}")


def make_anchor_toml(program_name: str) -> str:
    module_name = to_rust_name(program_name)
    cluster = config.SOLANA_CLUSTER
    return f'''[toolchain]
anchor_version = "{config.ANCHOR_VERSION}"

[features]
resolution = true
skip-lint = false

[programs.localnet]
{module_name} = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "{cluster}"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
'''


def make_cargo_workspace(program_name: str) -> str:
    return f'''[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
'''


def make_cargo_program(program_name: str) -> str:
    module_name = to_rust_name(program_name)
    return f'''[package]
name = "{module_name}"
version = "0.1.0"
description = "Generated by AnchorScaffold — LixerDev"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "{module_name}"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = {{ version = "0.30.0", features = ["init-if-needed"] }}
anchor-spl = {{ version = "0.30.0", features = ["token", "associated_token", "metadata"] }}
'''


def make_client_stub(program_name: str) -> str:
    module_name = to_rust_name(program_name)
    return f'''/**
 * {program_name} — Client SDK stub
 * Generated by AnchorScaffold — LixerDev
 *
 * Replace PROGRAM_ID with your deployed program address.
 */

import {{ Program, AnchorProvider, web3 }} from "@coral-xyz/anchor";
import {{ PublicKey, Connection, Keypair }} from "@solana/web3.js";

// Replace with your actual program ID after deployment
export const PROGRAM_ID = new PublicKey("11111111111111111111111111111111");

export function createProvider(connection: Connection, wallet: any): AnchorProvider {{
  return new AnchorProvider(connection, wallet, {{ commitment: "confirmed" }});
}}

// TODO: Import IDL from target/idl/{module_name}.json after building
// export const idl = require("../target/idl/{module_name}.json");
// export function createProgram(provider: AnchorProvider): Program {{
//   return new Program(idl, provider);
// }}
'''


def _migrations_stub(program_name: str) -> str:
    return f'''// Migrations for {program_name}
// Generated by AnchorScaffold — LixerDev

const anchor = require("@coral-xyz/anchor");

module.exports = async function (provider) {{
  anchor.setProvider(provider);
  // Add your migration logic here
  console.log("Deploying {program_name}...");
}};
'''


def _gitignore() -> str:
    return """.anchor
.DS_Store
target/
**/*.rs.bk
node_modules/
test-ledger/
.yarn/
"""


def _tsconfig() -> str:
    return '''{
  "compilerOptions": {
    "types": ["mocha", "chai"],
    "typeRoots": ["./node_modules/@types"],
    "lib": ["es2015"],
    "module": "commonjs",
    "target": "es6",
    "esModuleInterop": true
  }
}
'''


def _package_json(program_name: str) -> str:
    import json
    return json.dumps({
        "name": program_name,
        "version": "0.1.0",
        "description": f"Generated by AnchorScaffold",
        "scripts": {
            "build": "anchor build",
            "test": "anchor test",
            "deploy": "anchor deploy"
        },
        "dependencies": {
            "@coral-xyz/anchor": "^0.30.0",
            "@solana/web3.js": "^1.95.0",
            "@solana/spl-token": "^0.4.6"
        },
        "devDependencies": {
            "@types/bn.js": "^5.1.0",
            "@types/chai": "^4.3.0",
            "@types/mocha": "^9.0.0",
            "chai": "^4.3.4",
            "mocha": "^9.0.3",
            "ts-mocha": "^10.0.0",
            "typescript": "^5.0.0"
        }
    }, indent=2)
