"""
TestGenerator — generates TypeScript Anchor tests for each template.
"""

from src.models import TemplateKind
from src.parser import to_rust_name


class TestGenerator:
    def generate(self, kind: TemplateKind, program_name: str) -> str:
        module_name = to_rust_name(program_name)
        generators = {
            TemplateKind.STAKING:     self._staking_tests,
            TemplateKind.ESCROW:      self._escrow_tests,
            TemplateKind.VESTING:     self._vesting_tests,
            TemplateKind.DAO:         self._dao_tests,
            TemplateKind.LOTTERY:     self._lottery_tests,
            TemplateKind.MULTISIG:    self._multisig_tests,
            TemplateKind.MARKETPLACE: self._marketplace_tests,
            TemplateKind.LAUNCHPAD:   self._launchpad_tests,
            TemplateKind.CUSTOM:      self._custom_tests,
        }
        gen = generators.get(kind, self._custom_tests)
        return gen(program_name, module_name)

    def _header(self, program_name: str, module_name: str) -> str:
        return f'''/**
 * Tests for {program_name}
 * Generated by AnchorScaffold — LixerDev
 */

import * as anchor from "@coral-xyz/anchor";
import {{ Program, BN }} from "@coral-xyz/anchor";
import {{ PublicKey, Keypair, SystemProgram, LAMPORTS_PER_SOL }} from "@solana/web3.js";
import {{
  TOKEN_PROGRAM_ID,
  createMint,
  createAssociatedTokenAccount,
  mintTo,
  getAccount,
}} from "@solana/spl-token";
import {{ assert, expect }} from "chai";

describe("{program_name}", () => {{
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const program = anchor.workspace.{module_name.replace("_", "")} as Program<any>;
  const wallet = provider.wallet as anchor.Wallet;

'''

    def _staking_tests(self, name: str, module: str) -> str:
        return self._header(name, module) + f'''  let stakeMint: PublicKey;
  let rewardMint: PublicKey;
  let userStakeATA: PublicKey;
  let userRewardATA: PublicKey;
  let poolPDA: PublicKey;
  let vaultPDA: PublicKey;
  let rewardVaultPDA: PublicKey;
  let stakeAccountPDA: PublicKey;

  const REWARD_RATE = new BN(1_000_000); // 0.001 token/s per staked token (1e9 scaled)

  before(async () => {{
    // Create stake + reward mints
    stakeMint = await createMint(provider.connection, wallet.payer, wallet.publicKey, null, 9);
    rewardMint = await createMint(provider.connection, wallet.payer, wallet.publicKey, null, 9);

    userStakeATA = await createAssociatedTokenAccount(provider.connection, wallet.payer, stakeMint, wallet.publicKey);
    userRewardATA = await createAssociatedTokenAccount(provider.connection, wallet.payer, rewardMint, wallet.publicKey);

    await mintTo(provider.connection, wallet.payer, stakeMint, userStakeATA, wallet.payer, 1_000_000_000_000);

    [poolPDA] = PublicKey.findProgramAddressSync([Buffer.from("pool")], program.programId);
    [stakeAccountPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("stake"), wallet.publicKey.toBuffer()],
      program.programId
    );
  }});

  it("Initializes the staking pool", async () => {{
    await program.methods
      .initialize(REWARD_RATE)
      .accounts({{ pool: poolPDA, authority: wallet.publicKey, rewardMint, stakeMint, systemProgram: SystemProgram.programId }})
      .rpc();

    const pool = await program.account.stakingPool.fetch(poolPDA);
    assert.equal(pool.rewardRate.toNumber(), REWARD_RATE.toNumber(), "Reward rate should match");
    assert.equal(pool.totalStaked.toNumber(), 0, "Initial stake should be 0");
    console.log("  ✅ Pool initialized with reward rate:", REWARD_RATE.toNumber());
  }});

  it("Allows users to stake tokens", async () => {{
    const stakeAmount = new BN(100_000_000_000); // 100 tokens
    await program.methods
      .stake(stakeAmount)
      .accounts({{ pool: poolPDA, stakeAccount: stakeAccountPDA, userStakeAccount: userStakeATA, vault: vaultPDA, user: wallet.publicKey, tokenProgram: TOKEN_PROGRAM_ID, systemProgram: SystemProgram.programId }})
      .rpc();

    const stakeAcc = await program.account.stakeAccount.fetch(stakeAccountPDA);
    assert.equal(stakeAcc.stakedAmount.toNumber(), stakeAmount.toNumber(), "Staked amount should match");
    console.log("  ✅ Staked", stakeAmount.toNumber() / 1e9, "tokens");
  }});

  it("Accrues rewards over time", async () => {{
    // Simulate time passing
    await new Promise(r => setTimeout(r, 2000));

    const stakeAcc = await program.account.stakeAccount.fetch(stakeAccountPDA);
    console.log("  ℹ️ Pending rewards after 2s:", stakeAcc.pendingRewards?.toNumber() ?? "check on-chain");
  }});

  it("Allows claiming rewards", async () => {{
    await program.methods
      .claimRewards()
      .accounts({{ pool: poolPDA, stakeAccount: stakeAccountPDA, rewardVault: rewardVaultPDA, userRewardAccount: userRewardATA, user: wallet.publicKey, tokenProgram: TOKEN_PROGRAM_ID }})
      .rpc();
    console.log("  ✅ Rewards claimed successfully");
  }});

  it("Allows unstaking tokens", async () => {{
    const unstakeAmount = new BN(50_000_000_000); // 50 tokens
    await program.methods
      .unstake(unstakeAmount)
      .accounts({{ pool: poolPDA, stakeAccount: stakeAccountPDA, vault: vaultPDA, userStakeAccount: userStakeATA, user: wallet.publicKey, tokenProgram: TOKEN_PROGRAM_ID }})
      .rpc();
    console.log("  ✅ Unstaked", unstakeAmount.toNumber() / 1e9, "tokens");
  }});
}});
'''

    def _escrow_tests(self, name: str, module: str) -> str:
        return self._header(name, module) + f'''  const buyer = Keypair.generate();
  const seller = Keypair.generate();
  let escrowPDA: PublicKey;
  let escrowVaultPDA: PublicKey;
  let tokenMint: PublicKey;
  const escrowId = new BN(Date.now());

  before(async () => {{
    // Fund buyer and seller
    for (const kp of [buyer, seller]) {{
      await provider.connection.requestAirdrop(kp.publicKey, 2 * LAMPORTS_PER_SOL);
    }}
    await new Promise(r => setTimeout(r, 1000));
    tokenMint = await createMint(provider.connection, wallet.payer, wallet.publicKey, null, 6);
    [escrowPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("escrow"), buyer.publicKey.toBuffer(), escrowId.toArrayLike(Buffer, "le", 8)],
      program.programId
    );
  }});

  it("Creates an escrow", async () => {{
    const amount = new BN(1_000_000); // 1 USDC
    await program.methods.createEscrow(escrowId, amount, seller.publicKey, new BN(86400)).rpc();
    const escrow = await program.account.escrowAccount.fetch(escrowPDA);
    assert.equal(escrow.buyer.toBase58(), wallet.publicKey.toBase58());
    console.log("  ✅ Escrow created with amount:", amount.toNumber());
  }});

  it("Seller fulfills the escrow", async () => {{
    await program.methods.fulfill().accounts({{ escrow: escrowPDA, seller: seller.publicKey }}).signers([seller]).rpc();
    const escrow = await program.account.escrowAccount.fetch(escrowPDA);
    assert.isTrue(escrow.fulfilled, "Escrow should be marked fulfilled");
    console.log("  ✅ Escrow fulfilled by seller");
  }});

  it("Buyer approves release", async () => {{
    await program.methods.approveRelease().accounts({{ escrow: escrowPDA, buyer: wallet.publicKey }}).rpc();
    console.log("  ✅ Funds released to seller");
  }});
}});
'''

    def _vesting_tests(self, name: str, module: str) -> str:
        return self._header(name, module) + f'''  let vestingPDA: PublicKey;
  let tokenMint: PublicKey;
  const beneficiary = Keypair.generate();
  const vestingId = new BN(1);

  before(async () => {{
    await provider.connection.requestAirdrop(beneficiary.publicKey, LAMPORTS_PER_SOL);
    await new Promise(r => setTimeout(r, 500));
    tokenMint = await createMint(provider.connection, wallet.payer, wallet.publicKey, null, 9);
    [vestingPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("vesting"), beneficiary.publicKey.toBuffer(), vestingId.toArrayLike(Buffer, "le", 8)],
      program.programId
    );
  }});

  it("Creates a vesting schedule", async () => {{
    const now = Math.floor(Date.now() / 1000);
    const cliffSecs = new BN(60);       // 1 minute cliff
    const durationSecs = new BN(300);   // 5 minute vesting
    const totalAmount = new BN(1_000_000_000); // 1 token

    await program.methods.createVesting(vestingId, totalAmount, cliffSecs, durationSecs, beneficiary.publicKey).rpc();
    const vesting = await program.account.vestingAccount.fetch(vestingPDA);
    assert.equal(vesting.totalAmount.toNumber(), totalAmount.toNumber());
    console.log("  ✅ Vesting schedule created:", totalAmount.toNumber() / 1e9, "tokens");
  }});

  it("Cannot claim before cliff", async () => {{
    try {{
      await program.methods.claim().accounts({{ vesting: vestingPDA, beneficiary: beneficiary.publicKey }}).signers([beneficiary]).rpc();
      assert.fail("Should have thrown CliffNotReached");
    }} catch (e: any) {{
      assert.include(e.toString(), "CliffNotReached");
      console.log("  ✅ Correctly rejected claim before cliff");
    }}
  }});

  it("Can claim after cliff", async () => {{
    console.log("  ℹ️ Waiting for cliff period...");
    await new Promise(r => setTimeout(r, 65000)); // Wait past cliff
    await program.methods.claim().accounts({{ vesting: vestingPDA, beneficiary: beneficiary.publicKey }}).signers([beneficiary]).rpc();
    console.log("  ✅ Tokens claimed after cliff");
  }});
}});
'''

    def _dao_tests(self, name: str, module: str) -> str:
        return self._header(name, module) + f'''  let daoPDA: PublicKey;
  let proposalPDA: PublicKey;
  let voteRecordPDA: PublicKey;
  let govMint: PublicKey;
  const proposalId = new BN(1);

  before(async () => {{
    govMint = await createMint(provider.connection, wallet.payer, wallet.publicKey, null, 6);
    [daoPDA] = PublicKey.findProgramAddressSync([Buffer.from("dao")], program.programId);
    [proposalPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("proposal"), proposalId.toArrayLike(Buffer, "le", 8)],
      program.programId
    );
  }});

  it("Initializes the DAO", async () => {{
    const minVotes = new BN(1000);
    const votingPeriod = new BN(86400);
    await program.methods.initializeDao(govMint, minVotes, votingPeriod).accounts({{ dao: daoPDA, authority: wallet.publicKey, systemProgram: SystemProgram.programId }}).rpc();
    const dao = await program.account.daoConfig.fetch(daoPDA);
    assert.equal(dao.quorum.toNumber(), minVotes.toNumber());
    console.log("  ✅ DAO initialized");
  }});

  it("Creates a proposal", async () => {{
    await program.methods.createProposal(proposalId, "Increase reward rate", "Proposal to increase staking rewards by 20%").accounts({{ dao: daoPDA, proposal: proposalPDA, proposer: wallet.publicKey, systemProgram: SystemProgram.programId }}).rpc();
    const proposal = await program.account.proposal.fetch(proposalPDA);
    assert.equal(proposal.title, "Increase reward rate");
    console.log("  ✅ Proposal created");
  }});

  it("Allows voting", async () => {{
    [voteRecordPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("vote"), proposalPDA.toBuffer(), wallet.publicKey.toBuffer()],
      program.programId
    );
    await program.methods.castVote(true, new BN(500)).accounts({{ dao: daoPDA, proposal: proposalPDA, voteRecord: voteRecordPDA, voter: wallet.publicKey, systemProgram: SystemProgram.programId }}).rpc();
    const proposal = await program.account.proposal.fetch(proposalPDA);
    assert.isAbove(proposal.votesFor.toNumber(), 0);
    console.log("  ✅ Vote cast successfully");
  }});
}});
'''

    def _lottery_tests(self, name: str, module: str) -> str:
        return self._header(name, module) + f'''  let lotteryPDA: PublicKey;
  const lotteryId = new BN(1);
  const ticketPrice = new BN(0.1 * LAMPORTS_PER_SOL);

  before(async () => {{
    [lotteryPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("lottery"), lotteryId.toArrayLike(Buffer, "le", 8)],
      program.programId
    );
  }});

  it("Initializes a lottery", async () => {{
    const endTime = new BN(Math.floor(Date.now() / 1000) + 3600);
    await program.methods.initializeLottery(lotteryId, ticketPrice, endTime, new BN(1000)).accounts({{ lottery: lotteryPDA, authority: wallet.publicKey, systemProgram: SystemProgram.programId }}).rpc();
    const lottery = await program.account.lotteryAccount.fetch(lotteryPDA);
    assert.equal(lottery.ticketPrice.toNumber(), ticketPrice.toNumber());
    console.log("  ✅ Lottery initialized, ticket price:", ticketPrice.toNumber() / LAMPORTS_PER_SOL, "SOL");
  }});

  it("Allows buying tickets", async () => {{
    const [ticketPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("ticket"), lotteryPDA.toBuffer(), wallet.publicKey.toBuffer()],
      program.programId
    );
    await program.methods.buyTicket().accounts({{ lottery: lotteryPDA, ticket: ticketPDA, buyer: wallet.publicKey, systemProgram: SystemProgram.programId }}).rpc();
    const lottery = await program.account.lotteryAccount.fetch(lotteryPDA);
    assert.equal(lottery.totalTickets.toNumber(), 1);
    console.log("  ✅ Ticket purchased");
  }});

  it("Can draw winner (after end time)", async () => {{
    console.log("  ℹ️ Drawing winner using slot hash randomness");
    // In production, lottery end time must have passed
    // For testing, use a short end_time or mock
  }});
}});
'''

    def _multisig_tests(self, name: str, module: str) -> str:
        return self._header(name, module) + f'''  const owner1 = Keypair.generate();
  const owner2 = Keypair.generate();
  const owner3 = Keypair.generate();
  let multisigPDA: PublicKey;
  let txPDA: PublicKey;
  const txId = new BN(1);

  before(async () => {{
    for (const o of [owner1, owner2, owner3]) {{
      await provider.connection.requestAirdrop(o.publicKey, 2 * LAMPORTS_PER_SOL);
    }}
    await new Promise(r => setTimeout(r, 1000));
    [multisigPDA] = PublicKey.findProgramAddressSync([Buffer.from("multisig"), owner1.publicKey.toBuffer()], program.programId);
  }});

  it("Creates a 2-of-3 multisig", async () => {{
    const threshold = 2;
    const owners = [owner1.publicKey, owner2.publicKey, owner3.publicKey];
    await program.methods.createMultisig(owners, threshold).accounts({{ multisig: multisigPDA, creator: owner1.publicKey, systemProgram: SystemProgram.programId }}).signers([owner1]).rpc();
    const ms = await program.account.multisig.fetch(multisigPDA);
    assert.equal(ms.threshold, 2);
    assert.equal(ms.owners.length, 3);
    console.log("  ✅ 2-of-3 multisig created");
  }});

  it("Owner 1 creates a transaction", async () => {{
    [txPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("tx"), multisigPDA.toBuffer(), txId.toArrayLike(Buffer, "le", 8)],
      program.programId
    );
    const recipient = Keypair.generate().publicKey;
    await program.methods.createTransaction(txId, recipient, new BN(0.5 * LAMPORTS_PER_SOL)).accounts({{ multisig: multisigPDA, transaction: txPDA, proposer: owner1.publicKey, systemProgram: SystemProgram.programId }}).signers([owner1]).rpc();
    console.log("  ✅ Transaction proposed by owner 1");
  }});

  it("Owner 2 approves → reaches threshold → executes", async () => {{
    await program.methods.approve(txId).accounts({{ multisig: multisigPDA, transaction: txPDA, approver: owner2.publicKey }}).signers([owner2]).rpc();
    const tx = await program.account.multisigTransaction.fetch(txPDA);
    assert.isAbove(tx.approvals, 1);
    console.log("  ✅ Threshold reached, transaction can be executed");
  }});
}});
'''

    def _marketplace_tests(self, name: str, module: str) -> str:
        return self._header(name, module) + f'''  const seller = Keypair.generate();
  const buyer = Keypair.generate();
  let marketplacePDA: PublicKey;
  let listingPDA: PublicKey;
  let nftMint: PublicKey;

  before(async () => {{
    for (const kp of [seller, buyer]) {{
      await provider.connection.requestAirdrop(kp.publicKey, 5 * LAMPORTS_PER_SOL);
    }}
    await new Promise(r => setTimeout(r, 1000));
    nftMint = await createMint(provider.connection, wallet.payer, wallet.publicKey, null, 0);
    [marketplacePDA] = PublicKey.findProgramAddressSync([Buffer.from("marketplace")], program.programId);
  }});

  it("Initializes the marketplace", async () => {{
    const feeBps = 250; // 2.5%
    await program.methods.initializeMarketplace(feeBps).accounts({{ marketplace: marketplacePDA, authority: wallet.publicKey, systemProgram: SystemProgram.programId }}).rpc();
    const mp = await program.account.marketplaceConfig.fetch(marketplacePDA);
    assert.equal(mp.feeBps, 250);
    console.log("  ✅ Marketplace initialized with 2.5% fee");
  }});

  it("Seller lists an NFT", async () => {{
    const price = new BN(1 * LAMPORTS_PER_SOL);
    [listingPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("listing"), nftMint.toBuffer()],
      program.programId
    );
    await program.methods.listNft(price).accounts({{ marketplace: marketplacePDA, listing: listingPDA, nftMint, seller: seller.publicKey, systemProgram: SystemProgram.programId }}).signers([seller]).rpc();
    const listing = await program.account.listing.fetch(listingPDA);
    assert.equal(listing.price.toNumber(), price.toNumber());
    console.log("  ✅ NFT listed for", price.toNumber() / LAMPORTS_PER_SOL, "SOL");
  }});

  it("Buyer purchases the NFT", async () => {{
    await program.methods.buyNft().accounts({{ marketplace: marketplacePDA, listing: listingPDA, nftMint, buyer: buyer.publicKey, seller: seller.publicKey, systemProgram: SystemProgram.programId }}).signers([buyer]).rpc();
    console.log("  ✅ NFT purchased successfully");
  }});
}});
'''

    def _launchpad_tests(self, name: str, module: str) -> str:
        return self._header(name, module) + f'''  let salePDA: PublicKey;
  let contributionPDA: PublicKey;
  const contributor = Keypair.generate();
  const saleId = new BN(1);

  before(async () => {{
    await provider.connection.requestAirdrop(contributor.publicKey, 5 * LAMPORTS_PER_SOL);
    await new Promise(r => setTimeout(r, 500));
    [salePDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("sale"), saleId.toArrayLike(Buffer, "le", 8)],
      program.programId
    );
    [contributionPDA] = PublicKey.findProgramAddressSync(
      [Buffer.from("contribution"), salePDA.toBuffer(), contributor.publicKey.toBuffer()],
      program.programId
    );
  }});

  it("Initializes a token sale", async () => {{
    const now = Math.floor(Date.now() / 1000);
    await program.methods.initializeSale(
      saleId,
      new BN(now + 60),          // start_time
      new BN(now + 3600),        // end_time
      new BN(10 * LAMPORTS_PER_SOL), // soft_cap
      new BN(100 * LAMPORTS_PER_SOL), // hard_cap
      new BN(0.1 * LAMPORTS_PER_SOL), // min_contribution
      new BN(10 * LAMPORTS_PER_SOL),  // max_contribution
    ).accounts({{ sale: salePDA, authority: wallet.publicKey, systemProgram: SystemProgram.programId }}).rpc();
    console.log("  ✅ Token sale initialized");
  }});

  it("Contributor deposits SOL", async () => {{
    const amount = new BN(1 * LAMPORTS_PER_SOL);
    await program.methods.contribute(amount).accounts({{ sale: salePDA, contribution: contributionPDA, contributor: contributor.publicKey, systemProgram: SystemProgram.programId }}).signers([contributor]).rpc();
    const contrib = await program.account.contribution.fetch(contributionPDA);
    assert.equal(contrib.amount.toNumber(), amount.toNumber());
    console.log("  ✅ Contributed", amount.toNumber() / LAMPORTS_PER_SOL, "SOL");
  }});
}});
'''

    def _custom_tests(self, name: str, module: str) -> str:
        return self._header(name, module) + f'''  // Custom program tests
  // Generated by AnchorScaffold — LixerDev

  it("Initializes the program", async () => {{
    const [statePDA] = PublicKey.findProgramAddressSync([Buffer.from("state")], program.programId);
    await program.methods.initialize().accounts({{
      state: statePDA,
      authority: wallet.publicKey,
      systemProgram: SystemProgram.programId
    }}).rpc();
    const state = await program.account.programState.fetch(statePDA);
    assert.equal(state.authority.toBase58(), wallet.publicKey.toBase58());
    console.log("  ✅ Program initialized");
  }});

  // TODO: Add more tests for your custom instructions
}});
'''
